# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:

#- script: |
#    python -m pip install --upgrade pip setuptools wheel
#  displayName: 'Install tools'

- script: |
    which python
    python3 --version
    which pip3
    pip --version
  displayName: Check Python and pip versions
  enabled: false

- script: pip3 install -r requirements.txt
  displayName: Install requirements
  enabled: false

- script: |
    pip3 install pytest
    pip3 install pytest-cov
    pip3 list
    pip3 show pytest
    pip3 show pytest-cov
  displayName: Install pytest

- script: |
    pip3 list
  displayName: List pip packages
  enabled: false

- script: |
    pwd
  displayName: Show Path

- script: |
    sudo ln -s /home/vsts/.local/lib/python3.5/site-packages/pytest /usr/bin/pytest
    sudo ln -s /home/vsts/.local/lib/python3.5/site-packages/pytest-cov /usr/bin/pytest-cov
  displayName: Create Symlink
  enabled: false

- script: |
    echo $PATH
    whereis pytest
    whereis pytest-cov
  displayName: Check pytest and pytest-cov path

- script: |
    pwd
    python3 -m pytest test.py --doctest-modules --junitxml=junit/test-results.xml --cov=sample --cov-report=xml --cov-report=html 
#    python3 -m pytest unit_test.py --doctest-modules --junitxml=junit/test-results.xml
  displayName: 'Run Tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish test results for Python'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
  



