# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:

- script: |
    python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: |
    which python
    python3 --version
    which pip
    pip3 --version
  displayName: Check Python and pip versions

- script: |
    pip3 install pytest
    pip3 install pytest-cov
  displayName: Install pytest

- script: |
    pwd
  displayName: Show Path

#- script: |
#    which pytest
#    which pytest-cov
#  displayName: Check pytest and pytest-cov path

- script: |
    /usr/local/bin/pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
  displayName: 'Run Tests'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
